name: Unit Tests

on:
  push:
    branches: ["master", "**"]
  # pull_request:
  #   branches: ["master"]

jobs:
  build:
    runs-on: macos-latest

    strategy:
      matrix:
        node-version: [19.x]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }} and run all unit tests
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
          cache-dependency-path: "client/package-lock.json"
      - run: cd client; npm install; npm ci; npm test
